import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import { dummyFunction } from "./lib/actions";

const fira = Fira_Sans({subsets: ['latin'], weight: '400'});

export const metadata: Metadata = {
  title: "JhaeBlog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dummy = await dummyFunction()
  return (
    <html lang="en">
      <body className={`${fira.className} antialiased`}>
        <div className=" w-[100px]  bg-[#54A3A0] h-[300px] top-48 left-0 blur-3xl rounded-full absolute"></div>
        <div className=" w-[100px] z-50 bg-[#54A3A0] h-[300px]  bottom-0 right-0 blur-3xl rounded-full absolute"></div>
        {children}

        <script async src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"></script>
        <script async src="node_modules/@material-tailwind/html/scripts/ripple.js"></script>
      </body>
    </html>
  );
}
