import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/navigation/NavBar";

const fira = Fira_Sans({subsets: ['latin'], weight: '400'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fira.className} antialiased`}>
        <div className=" w-[100px]  bg-[#54A3A0] h-[300px] top-48 left-0 blur-3xl rounded-full absolute"></div>
        <div className=" w-[100px] z-50 bg-[#54A3A0] h-[300px]  bottom-0 right-0 blur-3xl rounded-full absolute"></div>
        <NavBar/>
        {children}</body>
    </html>
  );
}
